export const CHANGE_VIEWPORT = "CHANGE_VIEWPORT";
export const ADD_NEEDED_PLACES = "ADD_NEEDED_PLACES";
export const ADD_START_TO_NEEDED_PLACES_PATHES = "ADD_START_TO_NEEDED_PLACES_PATHES";
export const ADD_FOUNDED_PATH = "ADD_FOUNDED_PATH";
export const FILTER_CHECKED_PLACE = "FILTER_CHECKED_PLACE"